name:
  DeepMet
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pytorch
  - pytorch-cuda=11.8
  - jpype1
  - Click
  - rdkit
  - cdk
  - scikit-learn
  - conda-forge::openjdk
  - conda-forge::pyod
  - seaborn
