name:
  DeepMet
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - requests
  - numpy
  - scipy
  - scikit-learn=0.24.2
  - certifi
  - chardet
  - Click
  - cloudpickle
  - cycler
  - idna
  - kiwisolver
  - matplotlib
  - pandas
  - Pillow
  - pyparsing
  - python-dateutil
  - pytz
  - six
  - pytorch=1.7.0
  - torchvision=0.8.1
  - torchaudio=0.7.0
  - tqdm
  - ujson
  - urllib3
  - rdkit
  - jpype1=1.2.1
  - pyod=0.9.0
  - jupyter
