name: deepmet

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        python-version: [ 3.8 ]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup conda - Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: DeepMet
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          channels: anaconda, pytorch, conda-forge

      - name: Setup DeepMet
        shell: bash -l {0}
        run: |
          python setup.py install
          deepmet --help

      - name: Test with pytest-cov
        shell: bash -l {0}
        run: |
          conda install pytest==4.6.11 codecov pytest-cov -c conda-forge
          pytest --cov ./ --cov-config=.coveragerc --cov-report=xml
